#!/bin/bash
#Find available ports

#backend
cd ./backend 
echo "Started python virtual environment."
python3 -m venv venv
. venv/bin/activate
echo "Downloading backend requirements please wait..."
touch ./log.txt
pip install -r requirements.txt > ./log.txt 2>&1

# Frontend 
cd ../frontend
echo "Downloading frontend requirements please wait..."
touch ./log.txt
sed -i "s/localhost:[0-9]*/localhost:$port_b/" ./package.json
npm install > ./log.txt 2>&1